name: Enable Auto-Merge on PRs

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  pull-requests: write
  contents: write

jobs:
  enable-auto-merge:
    name: Enable Auto-Merge
    runs-on: ubuntu-latest
    # Only run on non-draft PRs
    if: github.event.pull_request.draft == false
    steps:
      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge --auto --squash ${{ github.event.pull_request.number }} --repo ${{ github.repository }}
